## Statements and Variables 

In [1]:
a <- 1 
b <- 2 

### Arithmetical operators

In [2]:
c <- a + b #addition

In [3]:
c

[1] 3

In [4]:
a - b # subtraction

[1] -1

In [5]:
a * b # multipication

[1] 2

In [6]:
b ** c # exponentiation

[1] 8

In [7]:
b %% c # modulo operator

[1] 2

### Relational operators

In [8]:
a < b 

[1] TRUE

In [9]:
b <= b

[1] TRUE

In [10]:
a > b

[1] FALSE

In [11]:
a == b

[1] FALSE

In [12]:
a != b

[1] TRUE

### Logical operators

In [13]:
( a > b ) || (a < b) # OR 

[1] TRUE

In [14]:
( a > b ) && (a < b) # AND

[1] FALSE

In [15]:
!(( a > b ) && (a < b)) # NOT

[1] TRUE

## Data Types

In [16]:
name <- "cusat"
print(class(name)) # type of variable 

[1] "character"


In [17]:
num <- 1.618
print(class(num)) # type of variable 

[1] "numeric"


In [18]:
num <- 16L
print(class(num)) # type of variable 

[1] "integer"


L tells R to store this as an integer.

In [19]:
t <- TRUE 
print(class(t)) # type of variable 

[1] "logical"


## Data Structure

### Vectors

- The concatenation function c() job is to combine multiple values into a single vector
- A vector is a sequence of similar data elements i.e., integer, double, logical, complex, etc.

In [20]:
workshop <- c(1,2,1,2,1,2,1,2)
workshop

[1] 1 2 1 2 1 2 1 2

In [21]:
gender <- c("f","f","f",NA,"m","m","m","m")
gender

[1] "f" "f" "f" NA  "m" "m" "m" "m"

In [22]:
a <- 1:10 #
a

[1]  1  2  3  4  5  6  7  8  9 10

In [23]:
seq(1, 10 ,2)

[1] 1 3 5 7 9

#### Operations

In [24]:
a + 10

[1] 11 12 13 14 15 16 17 18 19 20

In [25]:
a - 10

[1] -9 -8 -7 -6 -5 -4 -3 -2 -1  0

In [26]:
a <- c(1.5,3.8,6.7)
b <- c(2.1,8.9,6.7)

In [27]:
a < b

[1]  TRUE  TRUE FALSE

In [28]:
a == b

[1] FALSE FALSE  TRUE

#### Index

In [29]:
s=c("aa","bb","cc","dd","ee")
s[2]

[1] "bb"

In [30]:
s[c(2:4)]

[1] "bb" "cc" "dd"

In [31]:
s[c(TRUE,TRUE,FALSE,TRUE,FALSE)]

[1] "aa" "bb" "dd"

### Matrix

In [32]:
mymatrix <- matrix(c(1,1,5,1,2,1,4,1,2,2,4,3,3,10,3,4), nrow =4, ncol = 4, byrow = TRUE)

In [33]:
mymatrix

[,1] [,2] [,3] [,4]
[1,] 1     1   5    1   
[2,] 2     1   4    1   
[3,] 2     2   4    3   
[4,] 3    10   3    4

In [34]:
mymatrix[4,2]

[1] 10

In [35]:
mymatrix[c(1,3),]

[,1] [,2] [,3] [,4]
[1,] 1    1    5    1   
[2,] 2    2    4    3

### Lists

- A list is a special type of vector.
- It is used to store combinations of any other objects, even
other lists
- A list can contain many lists nested inside.
- Elements in the list are indexed by double brackets[[]].
- Single bracket[] will still return another list.
- Although you can use a list to store any R object, they are
most often used to store data in various forms, results from
functions such as regression equation parameters, and sets
of arguments to control functions.

In [42]:
my_list <- list(1,4,8,9)
x = list(1, "a", TRUE, c(1:8))

In [41]:
my_list

[[1]]
[1] 1

[[2]]
[1] 4

[[3]]
[1] 8

[[4]]
[1] 9

In [45]:
x = list(1, "a", TRUE, c(1:8))
x

[[1]]
[1] 1

[[2]]
[1] "a"

[[3]]
[1] TRUE

[[4]]
[1] 1 2 3 4 5 6 7 8

In [69]:
mylist = list(x = 1:15, y = c(TRUE,FALSE,TRUE,TRUE,FALSE))
mylist

$x
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15

$y
[1]  TRUE FALSE  TRUE  TRUE FALSE

In [70]:
mylist$x

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15

## BuiltIn Functions

In [36]:
is.integer(1L)

[1] TRUE

In [37]:
is.character(name)

[1] TRUE

In [38]:
as.integer(1.1)

[1] 1

In [39]:
is.matrix(mymatrix)

[1] TRUE

In [48]:
a <- c("aa","bb","cc","dd","ee")

In [49]:
length(a)

[1] 5

In [50]:
mode(a)

[1] "character"

In [52]:
which(a == 'aa') #The which() function will return the position of the elements

[1] 1

In [53]:
x1 <- c(1,5,4,7,2,1,5,3,1)

In [54]:
order(x1, decreasing = FALSE)

[1] 1 6 9 5 8 3 2 7 4

In [55]:
x1[order(x1, decreasing = FALSE)]

[1] 1 1 1 2 3 4 5 5 7

In [58]:
str(x1)

 num [1:9] 1 5 4 7 2 1 5 3 1


## Control Structure & Loops

These allow you to control the flow of execution of a script typically inside of a function

In [60]:
num_views <- 14
# Apply ifelse loop to check the number of views greater than 15 #
if (num_views > 15) {
print("This show is popular!")
}else{
print("This show is not popular!")
}

[1] "This show is not popular!"


### Loops

In a **for** loop a looping vector is assigned a value which is iterated in a loop for certain
number of times. For each iteration the statement is evaluated.

In [61]:
x <- c(2,5,3,9,8,11,6, 4,8,9,
1,3,4,6,7,5,21,12,13,14,10)
# initiate count with 0 #
count <- 0
for (i in x)
{
if(i %% 2 == 0)
count = count+1
}
print(count)

[1] 10


The **while** continues executing a block of codes until a specific condition
is met.

In [62]:
speed <- 84
# apply while loop to check the condition #
while (speed > 30 ) {
print("Slow down!")
speed = speed-5
}

[1] "Slow down!"
[1] "Slow down!"
[1] "Slow down!"
[1] "Slow down!"
[1] "Slow down!"
[1] "Slow down!"
[1] "Slow down!"
[1] "Slow down!"
[1] "Slow down!"
[1] "Slow down!"
[1] "Slow down!"


### Apply Functuions

In [63]:
mymatrix

[,1] [,2] [,3] [,4]
[1,] 1     1   5    1   
[2,] 2     1   4    1   
[3,] 2     2   4    3   
[4,] 3    10   3    4

In [64]:
apply(mymatrix,2,sum)

[1]  8 14 16  9

In [72]:
mylist

$x
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15

$y
[1]  TRUE FALSE  TRUE  TRUE FALSE

In [73]:
lapply(mylist, mean)

$x
[1] 8

$y
[1] 0.6

In [77]:
sapply(mylist, mean)

x   y 
8.0 0.6

## Functions 

In [80]:
tfunc <- function(a){
    v <- 1 : 10
    if(a > 10){
    return(v + a)
    }
    else{
    return(v + a + 10)       
    }
}


In [83]:
tfunc(-10)

[1]  1  2  3  4  5  6  7  8  9 10

In [84]:
fib <- function(n){
    if(n <= 2)
        return(1)
    return(fib(n-1) + fib(n-2))
}

In [85]:
fib(4)

[1] 3

**Exercise 2**

- Write function to find the nth prime number ? 
- find the 100001'th prime number