## Statements and Variables 

In [1]:
a <- 1 
b <- 2 

In [2]:
a

[1] 1

In [3]:
b

[1] 2

In [4]:
a + b

[1] 3

### Arithmetical operators

In [6]:
c <- a + 3
c

[1] 4

In [7]:
print(c)

[1] 4


In [8]:
c = a + b
c

[1] 3

In [2]:
c <- a + b #addition

In [3]:
c

[1] 3

In [9]:
a - b # subtraction

[1] -1

In [10]:
a * b # multipication

[1] 2

In [11]:
b ** c # exponentiation

[1] 8

In [12]:
8 %% 3

[1] 2

In [7]:
b %% c # modulo operator

[1] 2

### Relational operators

In [8]:
a < b 

[1] TRUE

In [13]:
1 > 2

[1] FALSE

In [14]:
4 < 4

[1] FALSE

In [9]:
b <= b

[1] TRUE

In [17]:
4 == 4

[1] TRUE

In [18]:
4 != 3

[1] TRUE

In [19]:
4 != 4

[1] FALSE

In [10]:
a > b

[1] FALSE

In [11]:
a == b

[1] FALSE

In [12]:
a != b

[1] TRUE

### Logical operators

In [20]:
TRUE || FALSE

[1] TRUE

In [21]:
TRUE || TRUE

[1] TRUE

In [13]:
( a > b ) || (a < b) # OR 

[1] TRUE

In [22]:
TRUE && FALSE

[1] FALSE

In [14]:
( a > b ) && (a < b) # AND

[1] FALSE

In [24]:
!TRUE

[1] FALSE

In [15]:
!(( a > b ) && (a < b)) # NOT

[1] TRUE

## Data Types

In [16]:
name <- "cusat"
print(class(name)) # type of variable 

[1] "character"


In [17]:
num <- 1.618
print(class(num)) # type of variable 

[1] "numeric"


In [18]:
num <- 16L
print(class(num)) # type of variable 

[1] "integer"


L tells R to store this as an integer.

In [19]:
t <- TRUE 
print(class(t)) # type of variable 

[1] "logical"


## Data Structure

### Vectors

- The concatenation function c() job is to combine multiple values into a single vector
- A vector is a sequence of similar data elements i.e., integer, double, logical, complex, etc.

In [20]:
workshop <- c(1,2,1,2,1,2,1,2)
workshop

[1] 1 2 1 2 1 2 1 2

In [21]:
gender <- c("f","f","f",NA,"m","m","m","m")
gender

[1] "f" "f" "f" NA  "m" "m" "m" "m"

In [22]:
a <- 1:10 #
a

[1]  1  2  3  4  5  6  7  8  9 10

In [23]:
seq(1, 10 ,2)

[1] 1 3 5 7 9

#### Operations

In [28]:
a <- 1:20
a

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20

In [27]:
a + 10

[1] 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30

In [29]:
a - 10

[1] -9 -8 -7 -6 -5 -4 -3 -2 -1  0  1  2  3  4  5  6  7  8  9 10

In [26]:
a <- c(1.5,3.8,6.7)
b <- c(2.1,8.9,6.7)

In [27]:
a < b

[1]  TRUE  TRUE FALSE

In [28]:
a == b

[1] FALSE FALSE  TRUE

#### Index

In [31]:
rnorm(12)

[1]  1.1695815 -1.8465622 -0.9526290  0.4689595 -0.2745404  1.1855866
 [7]  3.0181363 -1.2502992 -0.3649603  0.9677072 -0.4889744 -0.2483099

In [32]:
s=c("aa","bb","cc","dd","ee")
s

[1] "aa" "bb" "cc" "dd" "ee"

In [33]:
s[1]

[1] "aa"

In [34]:
s[2]

[1] "bb"

In [36]:
2:4

[1] 2 3 4

In [35]:
s[2:4]

[1] "bb" "cc" "dd"

In [38]:
s[c(TRUE,TRUE,FALSE,TRUE,FALSE)]

[1] "aa" "bb" "dd"

### Matrix

In [39]:
mymatrix <- matrix(1:16, nrow =4, ncol = 4, byrow = TRUE)

In [40]:
mymatrix

[,1] [,2] [,3] [,4]
[1,]  1    2    3    4  
[2,]  5    6    7    8  
[3,]  9   10   11   12  
[4,] 13   14   15   16

In [42]:
help(matrix)

In [50]:
mymatrix <- matrix(1:16, nrow =4, ncol = 4)
mymatrix

[,1] [,2] [,3] [,4]
[1,] 1    5     9   13  
[2,] 2    6    10   14  
[3,] 3    7    11   15  
[4,] 4    8    12   16

In [51]:
mymatrix[4,2]

[1] 8

In [54]:
mymatrix[4,4]

[1] 16

In [56]:
mymatrix[,4]

[1] 13 14 15 16

In [53]:
mymatrix[1:2,1:2]

[,1] [,2]
[1,] 1    5   
[2,] 2    6

### Lists

- A list is a special type of vector.
- It is used to store combinations of any other objects, even
other lists
- A list can contain many lists nested inside.
- Elements in the list are indexed by double brackets[[]].
- Single bracket[] will still return another list.
- Although you can use a list to store any R object, they are
most often used to store data in various forms, results from
functions such as regression equation parameters, and sets
of arguments to control functions.

In [49]:
help(list)

In [44]:
my_list <- list(1,4,8,9)
x = list(1, "a", TRUE, c(1:8))

In [45]:
my_list

[[1]]
[1] 1

[[2]]
[1] 4

[[3]]
[1] 8

[[4]]
[1] 9

In [46]:
x

[[1]]
[1] 1

[[2]]
[1] "a"

[[3]]
[1] TRUE

[[4]]
[1] 1 2 3 4 5 6 7 8

In [45]:
x = list(1, "a", TRUE, c(1:8))
x

[[1]]
[1] 1

[[2]]
[1] "a"

[[3]]
[1] TRUE

[[4]]
[1] 1 2 3 4 5 6 7 8

In [76]:
mylist = list(x = 1:15, y = c(TRUE,FALSE,TRUE,TRUE,FALSE))
mylist

$x
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15

$y
[1]  TRUE FALSE  TRUE  TRUE FALSE

In [48]:
mylist$y

[1]  TRUE FALSE  TRUE  TRUE FALSE

In [70]:
mylist$x

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15

### Factors

In [2]:
x1 <- c("Dec", "Apr", "Jan", "Mar")

In [3]:
month_levels <- c(
  "Jan", "Feb", "Mar", "Apr", "May", "Jun", 
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
)

In [4]:
y1 <- factor(x1, levels = month_levels)
y1

[1] Dec Apr Jan Mar
Levels: Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec

In [5]:
sort(y1)

[1] Jan Mar Apr Dec
Levels: Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec

## BuiltIn Functions

In [36]:
is.integer(1L)

[1] TRUE

In [58]:
name <- "nithin"

In [59]:
is.character(name)

[1] TRUE

In [38]:
as.integer(1.1)

[1] 1

In [39]:
is.matrix(mymatrix)

[1] TRUE

In [48]:
a <- c("aa","bb","cc","dd","ee")

In [49]:
length(a)

[1] 5

In [50]:
mode(a)

[1] "character"

In [60]:
a

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20

In [61]:
which(a == 20) #The which() function will return the position of the elements

[1] 20

In [62]:
x1 <- c(1,5,4,7,2,1,5,3,1)

In [69]:
help(order)

In [68]:
order(x1, decreasing = TRUE)

[1] 4 2 7 3 8 5 1 6 9

In [71]:
c1

[1] 122

In [67]:
x1[order(x1)]

[1] 1 1 1 2 3 4 5 5 7

In [74]:
x1

[1] 1 5 4 7 2 1 5 3 1

In [58]:
str(x1)

 num [1:9] 1 5 4 7 2 1 5 3 1


In [77]:
mylist

$x
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15

$y
[1]  TRUE FALSE  TRUE  TRUE FALSE

In [78]:
str(mylist)

List of 2
 $ x: int [1:15] 1 2 3 4 5 6 7 8 9 10 ...
 $ y: logi [1:5] TRUE FALSE TRUE TRUE FALSE


## Control Structure & Loops

These allow you to control the flow of execution of a script typically inside of a function

In [83]:
if (FALSE){
    print("cusat FDA")

}else{
    print("jupyter")
}

[1] "jupyter"


In [85]:
num_views <- 140
# Apply ifelse loop to check the number of views greater than 15 #
if (num_views > 15) {
print("This show is popular!")
}else{
print("This show is not popular!")
}

[1] "This show is popular!"


### Loops

In a **for** loop a looping vector is assigned a value which is iterated in a loop for certain
number of times. For each iteration the statement is evaluated.

In [87]:
x <- 100:110
x

[1] 100 101 102 103 104 105 106 107 108 109 110

In [89]:
for (i in x){
    print(i + 100)
}

[1] 200
[1] 201
[1] 202
[1] 203
[1] 204
[1] 205
[1] 206
[1] 207
[1] 208
[1] 209
[1] 210


In [61]:
x <- c(2,5,3,9,8,11,6, 4,8,9,1,3,4,6,7,5,21,12,13,14,10)
# initiate count with 0 #
count <- 0
for (i in x)
{
if(i %% 2 == 0)
count = count+1
}
print(count)

[1] 10


The **while** continues executing a block of codes until a specific condition

is met.

<img src="https://upload.wikimedia.org/wikipedia/commons/4/43/While-loop-diagram.svg">

In [110]:

x = 10
while(x < 100){
    print(x)
    x <- x +20
}

[1] 10
[1] 30
[1] 50
[1] 70
[1] 90


- While is a condition based 


In [115]:

speed <- 84

while (speed > 30 ) {
    print("Slow down!")
    speed = speed-20
}

[1] "Slow down!"
[1] "Slow down!"
[1] "Slow down!"


### Apply Functuions

<img src="https://www.guru99.com/images/r_programming/032918_0401_applysapply1.png">

In [100]:
mymatrix

[,1] [,2] [,3] [,4]
[1,] 1    5     9   13  
[2,] 2    6    10   14  
[3,] 3    7    11   15  
[4,] 4    8    12   16

In [106]:
sum(c(1,2,2,2))

[1] 7

In [107]:
mean(1:10)

[1] 5.5

In [101]:
sum(1:10)

[1] 55

In [105]:
apply(mymatrix,2,sum)

[1] 10 26 42 58

In [72]:
mylist

$x
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15

$y
[1]  TRUE FALSE  TRUE  TRUE FALSE

In [73]:
lapply(mylist, mean)

$x
[1] 8

$y
[1] 0.6

In [77]:
sapply(mylist, mean)

x   y 
8.0 0.6

## Functions 

In [80]:
tfunc <- function(a){
    v <- 1 : 10
    if(a > 10){
    return(v + a)
    }
    else{
    return(v + a + 10)       
    }
}


In [83]:
tfunc(-10)

[1]  1  2  3  4  5  6  7  8  9 10

In [84]:
fib <- function(n){
    if(n <= 2)
        return(1)
    return(fib(n-1) + fib(n-2))
}

In [85]:
fib(4)

[1] 3

**Exercise 2**

- Write function to find the nth prime number ? 
- find the 100001'th prime number